function  surface_parcellation_cifti_smallwall_wateredge_remover_evan2(avgcorrfilename,outputdir,hems,edges)

%function  surface_parcellation_cifti_smallwall_wateredge_remover_evan2(avgcorrfilename,outputdir,hems,edges)

%Generate gradient-based parcellation on surface registered subject data
% This script requires a parcellation cohortfile file. The cohortfile includes
% a list of the subject names, the functional volume to be parcellated including
% its path, and the directory where the subject's surface is (as generated by 
% Freesurfer and registered to fs_LR space), formatted as:
% 
% subjectname funcpath/funcvol surfdir
% 
% e.g. 
%
% vc33416 /data/cn4/laumannt/vc33416_rest1.4dfp.img /data/cn4/segmentation/freesurfer5_supercomputer/FREESURFER_fs_LR/vc33416/7112b_fs_LR
%
% With 'tmasktype', users can enter a tmasklist.txt as created by
% fcimage_analysis to mask out timepoints in their data. Enter 'none' if no
% temporal mask is needed.
% If 'smooth' is set to  'yes' data will be smoothed along the cortical
% surface after surface projection. Enter 'no' if no surface smoothing is
% desired.
% With 'hems', users can specify that either the 'LEFT', 'RIGHT', or 'BOTH'
% hemispheres be parcellated.
% If 'edges' is set to 'yes' a final non-maxima suppression step will be
% applied to the gradient maps and an edge frequency map will be output in
% addition to an average gradient map. Enter 'no' if edge detection is not
% desired.
% This version of surface parcellation will always average correlation data
% from all subjects, generating a single gradient and/or edge map for the
% group.
% TOL 01/25/13

% smoothnum = 2.55;
% mask4dfp='/data/cn4/laumannt/Standard/glm_atlas_mask_333.4dfp.img';
 workbenchdir = 'env nice -n 10 /data/cn4/laumannt/workbench/bin_linux64/';
% %roidir = '/data/cn4/laumannt/subcortical_mask';
 roidir = '/data/cn5/selfRegulation/V4Process_nosmooth/';
 HEMS = {'L';'R'};
 hemname = {'LEFT';'RIGHT'};
 hemname_low = {'left';'right'};


switch hems
    case 'LEFT'
        h = 1;
    case 'RIGHT'
        h = 2;
     case 'BOTH'
         h = [1:2];
end
% 
% % Make output folder
% system(['mkdir ' outputdir])

for hem = h
    
    
maskname = [roidir '/' HEMS{hem} '.atlasroi_group_proj.func.gii'];
    
mask = gifti(maskname); mask = mask.cdata;
maskL = gifti([roidir '/L.atlasroi_group_proj.func.gii']); maskL = maskL.cdata;

%disp('Selecting verts for this hemisphere')
%
% system([workbenchdir '/wb_command -cifti-convert -to-gifti-ext ' avgcorrfilename ' ' outputdir '/Temp.func.gii']); 
% avgcorr = gifti([outputdir '/Temp.func.gii']); avgcorr = avgcorr.cdata;
% avgcorr = avgcorr([1:nnz(mask)] + (nnz(maskL)*strcmp('R',HEMS{hem})) , :);
% save(gifti(single(avgcorr)),[outputdir '/Temp.func.gii'],'ExternalFileBinary')
% system([workbenchdir '/wb_command -cifti-convert -from-gifti-ext ' outputdir '/Temp.func.gii ' outputdir '/avg_corr_' HEMS{hem} '.dconn.nii']); 
% delete([outputdir '/Temp.func.gii*'])


    %Calculate corr of corr
    disp('Calculating corr of corr')
    %system([workbenchdir '/wb_command -cifti-correlation ' outputdir '/avg_corr_' HEMS{hem} '.dtseries.nii ' outputdir '/avg_corrofcorr_' HEMS{hem} '.dconn.nii'])
    system([workbenchdir '/wb_command -cifti-correlation ' avgcorrfilename ' ' outputdir '/avg_corrofcorr_' HEMS{hem} '.dconn.nii'])
    
    disp('done')
 
    % Calculate gradients       
    atlasdir = '/data/cn4/laumannt/standard_mesh_atlases/Conte69_atlas.LR.32k_fs_LR_glasser';
    midsurf_32k = [atlasdir '/fsaverage_LR32k/Conte69.' HEMS{hem} '.midthickness.32k_fs_LR.surf.gii'];

    disp('Calculating gradient')
      gradsname = ['avgcorrofcorr_allgrad_' HEMS{hem}];  
    system([workbenchdir '/wb_command -cifti-gradient ' outputdir '/avg_corrofcorr_' HEMS{hem} '.dconn.nii COLUMN ' outputdir '/' gradsname '.dconn.nii -' hemname_low{hem} '-surface ' midsurf_32k ' -surface-presmooth 2.55']);
    
    % Average gradients
    system([workbenchdir '/wb_command -cifti-reduce ' outputdir '/' gradsname '.dconn.nii MEAN ' outputdir '/' gradsname '_avg.dtseries.nii'])

    % Smooth gradients before edge detection
    disp('Smoothing gradient')
      smooth = 2.55;
    system([workbenchdir '/wb_command -cifti-smoothing ' outputdir '/' gradsname '.dconn.nii ' num2str(smooth) ' 0 COLUMN ' outputdir '/' gradsname '_smooth' num2str(smooth) '.dconn.nii -' hemname_low{hem} '-surface ' midsurf_32k]);
   
    % Average smooth gradients
    system([workbenchdir '/wb_command -cifti-reduce ' outputdir '/' gradsname '_smooth' num2str(smooth) '.dconn.nii MEAN ' outputdir '/' gradsname '_smooth' num2str(smooth) '_avg.dtseries.nii'])
    
    % Load medial wall mask
    medial_wall = gifti([maskname]);   
    %medial_wall = gifti(['/data/hcp-zfs/home/laumannt/120_parcellation/medial_exclude_' HEMS{hem} '.func.gii']);
    medial_wall = medial_wall.cdata;  
    
    % Convert cifti to load into matlab
    system([workbenchdir '/wb_command -cifti-convert -to-gifti-ext ' outputdir '/' gradsname '_smooth' num2str(smooth) '.dconn.nii ' outputdir '/' gradsname '_smooth' num2str(smooth) '.func.gii']);

    grads = gifti([outputdir '/avgcorrofcorr_allgrad_' HEMS{hem} '_smooth' num2str(smooth) '.func.gii']);
    fullgrads = zeros(32492,nnz(medial_wall));
    fullgrads(logical(medial_wall),:) = grads.cdata; 
    clear grads
    
    % For nonmax edge calculation
    atlasdir = '/data/cn4/laumannt/standard_mesh_atlases/Conte69_atlas.LR.32k_fs_LR_glasser';
    specfile = [atlasdir '/fsaverage_LR32k/Conte69.' HEMS{hem} '.32k_fs_LR.c5.spec'];
    
    % Calculate edge maps
    switch edges
        case 'no'
        case 'yes'   
            disp('Calculating edges')
            fullgrads_medial = fullgrads;
            fullgrads_medial(logical(~medial_wall),:) = 1000;
            minimametrics = metric_minima_all(fullgrads_medial,3); 
            clear fullgrads_medial
            %Original water edge
            labels = watershed_algorithm_all_par_evan(fullgrads,minimametrics,200,1);
            labels_avg = mean(labels==0,2);
            save(gifti(single(labels_avg)),[outputdir '/' gradsname '_smooth' num2str(smooth) '_wateredge_avg.func.gii']);
            
            save([outputdir 'labels_' HEMS{hem}],'labels','-v7.3');
            
            %Water edge with below threshold edges removed
            labels = watershed_edgeremover(labels,fullgrads,0.01);
            labels_avg = mean(labels,2);
            save(gifti(single(labels_avg)),[outputdir '/' gradsname '_smooth' num2str(smooth) '_wateredge_thresh0.01_avg.func.gii']);
            
            %Nonmaxima suppression-based edges
%            surface_edges_all_test_faster(fullgrads,specfile,outputdir,[gradsname '_smooth' num2str(smooth) '_edge_avg'],1);
    end
    
    system(['rm ' outputdir '/avg_corrofcorr_' HEMS{hem} '.dconn.nii'])
   % system(['rm ' outputdir '/' gradsname '_smooth' num2str(smooth) '.func.*']);
    system(['rm ' outputdir '/' gradsname '.dconn.nii']);
    system(['rm ' outputdir '/' gradsname '_smooth' num2str(smooth) '.dconn.nii'])

end
%exit